[project]
name = "pybackend"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Conrado", email = "csilvamiranda@cloudera.com"},
]
dependencies = []
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "TBD"}


[tool.pdm]
distribution = false
